# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
        . /etc/bashrc
fi

export GOPATH={{go_path}}/
export CDPATH=.:~:{{openshift_path}}
export PATH=$PATH:{{openshift_bin_path}}/
export EDITOR='emacs-nox'
alias sd='sudo docker'
alias em='emacs-nox'
