- name: restart docker
  service: name=docker state=restarted

- name: restart systemctl
  command: /usr/bin/systemctl daemon-reload

- name: restart openshift
  command: /usr/sbin/service openshift restart
