export GOPATH={{go_path}}/src
export CDPATH=.:~:{{openshift_path}}
export PATH=$PATH:{{origin_path}}/_output/local/bin/linux/amd64/
export EDITOR='emacs-nox'
export sd='sudo docker'
export em='emacs-nox'
