---
- name: Update All packages
  become: yes
  become_user: root
  dnf: >
    name=* state=latest
  when: ansible_os_family == "RedHat"

- name: Install common packages
  become: yes
  become_user: root
  dnf: >
    name={{ item }} state=latest
  when: ansible_os_family == "RedHat"
  with_items:
    - "augeas"
    - "bzr"
    - "bridge-utils"
    - "bzip2"
    - "bind"
    - "btrfs-progs-devel"
    - "ctags"
    - "device-mapper-devel"
    - "ethtool"
    - "e2fsprogs"
    - "fontconfig"
    - "glibc-static"
    - "gnuplot"
    - "httpie"
    - "hg"
    - "jq"
    - "libselinux-devel"
    - "libnetfilter_queue-devel"
    - "make"
    - "mlocate"
    - "ntp"
    - "openldap-clients"
    - "openvswitch"
    - "rubygems"
    - "screen"
    - "socat"
    - "sqlite-devel"
    - "sysstat"
    - "tig"
    - "tmux"
    - "unzip"
    - "vim"
    - "wget"
    - "xfsprogs"
    - "Xvfb"
    - "git"
    - "polkit"
    - "gcc"
    - "make"
    - "automake"
    - "gcc-c++"
    - "kernel-devel"
    - "python"
    - "python-virtualenv"
    - "python-devel"
    - "htop"
    - "nload"
    - "mlocate"
    - "policycoreutils-python"
    - "tmux"
    - "net-tools"
    - "emacs-nox"
    - "httpd-tools"
    - "wget"
    - "curl"
    - "bind-utils"
    - "nc"
    - "docker"
    - "golang"
    - "python3-devel"
    - "ruby"
    - "git"
    - "ethtool"
    - "nodejs"
    - "npm"

- name: Install custom .files
  template: src=files/bashrc dest={{home_path}}/.bashrc group={{default_user_group}} owner={{default_user}}

- name: Remove current setup
  command: /usr/bin/rm -rf {{home_path}}/.emacs.d

- name: Fetch emacs setup repo
  git: repo=https://github.com/PI-Victor/.emacs.d.git dest={{home_path}}/.emacs.d clone=yes

- name: Copy the .emacs to ~
  command: cp -p {{home_path}}/.emacs.d/.emacs {{home_path}}/

- name: Fetch tmux setup repo
  git: repo=https://github.com/PI-Victor/.tmux_conf.git dest={{home_path}}/.tmux_conf clone=yes

- name: Copy the .tmux.conf to ~
  command: cp -p {{home_path}}/.tmux_conf/.tmux.conf {{home_path}}/

- name: Install bower globally
  command: /usr/bin/npm install -g bower --allow-root

- name: Switch SElinux to permissive mode.
  selinux: policy=targeted state=permissive

- name: Ensure docker is added to systemctl
  become: yes
  become_user: root
  service: name=docker enabled=yes state=started

- name: Copy custom docker config and restart service
  template: src=templates/docker dest=/etc/sysconfig/docker
  template: src=templates/docker-storage dest=/etc/sysconfig/docker-storage
  notify:
    - restart docker

- name: Ensure that firewalld is off
  become: yes
  become_user: root
  service: name=firewalld enabled=no state=stopped

- name: Remove dnf cached files
  command: /usr/bin/dnf clean all
